export const ERRORS = {
  GENERIC: "GENERIC_ERROR",
  INCORRECT_INPUT_VALUE: "INCORRECT_INPUT_VALUE",
  INCORRECT_ARGUMENT_RECIEVED: "INCORRECT_ARGUMENT_RECIEVED",
  NETWORK: "NETWORK_ERROR",
  REMOTE_DATA_NOT_FOUND: "REMOTE_DATA_NOT_FOUND",
} as const;
